### ISSUE TITLE
Custom extension pack not saved

### ISSUE THREAD

**Issue by steve-bate** [hayden-fr/vscode-extension-pack-manager#3]
I've tried creating custom extension packs with this plugin (v0.2.1) and have not been successful. I am able to use the creation dialog to define the name, description, and included extensions. However, the command to view custom extension packs shows an empty list.

VS Code details:
```
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:07:18.579Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
```

**Comment by Zeal-L** [comment]
Same

**Comment by hayden-cn** [comment]
Sorry I don't have Mac so can't test and fix. I think this may be caused by insufficient permissions that it cannot write data on the local disk.

**Comment by trouni** [comment]
Same for me. Seems like [this fork](https://marketplace.visualstudio.com/items?itemName=zyg.extension-pack-manager2) fixed it though.

**Comment by texastoland** [comment]
Still maintained? Accepting PRs?

**Comment by hayden-cn** [comment]
> Still maintained? Accepting PRs?

yes

**Comment by mcwolf233** [comment]
how to solve insufficient permissions?hurry!

**Comment by texastoland** [comment]
I switched to an alternative extension.
